services:
  postgres:
    image: postgres:16
    container_name: postgres-foodvlog
    environment:
      POSTGRES_USER: sai_hruthik_reddy
      POSTGRES_PASSWORD: gurusahib466
      POSTGRES_DB: foodvloggingDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sai -d foodvlog"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data: